# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: lukaszgodula/angular-chrome-headless-docker-node-12:latest

cache:
  paths:
  - node_modules/

before_script:
  - npm install

test:
  script:
    - npm test
