# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:12

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/

before_script:
  - npm install

build:
  script:
    - npm run start
    - npm run start-vue
  artifacts:
    paths:
      - "generated-with-style/"
      - "generated-without-style/"
      - "gen-vue/"

pages:
  stage: deploy
  script:
    - npm run build
  artifacts:
    paths:
      - public
  only:
    - master
