# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: trion/ng-cli-karma:8.2.2

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/

before_script:
  - npm install

test:
  script:
    - npm test
build:
  script:
    - ng build --project="openbridge-demo"
    - ng build --project="openbridge-components"
    - npm run build:lib
  artifacts:
    paths:
      - "dist/"
