import './view/bar/bar-horizontal-small'
import './view/bar/bar-horizontal-medium'
import './view/bar/bar-horizontal-large'
import './view/bar/bar-horizontal-positive-small'
import './view/bar/bar-horizontal-positive-medium'
import './view/bar/bar-horizontal-positive-large'
import './view/bar/bar-vertical-small'
import './view/bar/bar-vertical-medium'
import './view/bar/bar-vertical-large'
import './view/bar/bar-vertical-positive-small'
import './view/bar/bar-vertical-positive-medium'
import './view/bar/bar-vertical-positive-large'

import './view/hdg/hdg-small'
import './view/hdg/hdg-medium'
import './view/hdg/hdg-large'

import './view/pitch-roll/pitch-small'
import './view/pitch-roll/pitch-medium'
import './view/pitch-roll/pitch-large'
import './view/pitch-roll/roll-small'
import './view/pitch-roll/roll-medium'
import './view/pitch-roll/roll-large'
import './view/pitch-roll/combined-small'
import './view/pitch-roll/combined-medium'
import './view/pitch-roll/combined-large'

import './view/rot/rot-circle-small'
import './view/rot/rot-circle-medium'
import './view/rot/rot-circle-large'
import './view/rot/rot-flat-small'
import './view/rot/rot-flat-medium'
import './view/rot/rot-flat-large'
import './view/rot/rot-flat-bar-small'
import './view/rot/rot-flat-bar-medium'
import './view/rot/rot-flat-bar-large'

import './view/rudder/rudder-small'
import './view/rudder/rudder-medium'
import './view/rudder/rudder-large'

import './view/sog/speedometer-medium'

import './view/thrusters/azimuth-small'
import './view/thrusters/azimuth-medium'
import './view/thrusters/azimuth-large'
import './view/thrusters/main-engine-small'
import './view/thrusters/main-engine-medium'
import './view/thrusters/main-engine-large'
import './view/thrusters/thruster-element-small'
import './view/thrusters/thruster-element-medium'
import './view/thrusters/thruster-element-large'
import './view/thrusters/tunnel-thruster-small'
import './view/thrusters/tunnel-thruster-medium'
import './view/thrusters/tunnel-thruster-large'

import './view/watchface/watchface-small'
import './view/watchface/watchface-medium'
import './view/watchface/watchface-large'
