import './bar/bar-horizontal-small'
import './bar/bar-horizontal-medium'
import './bar/bar-horizontal-large'
import './bar/bar-horizontal-positive-small'
import './bar/bar-horizontal-positive-medium'
import './bar/bar-horizontal-positive-large'
import './bar/bar-vertical-small'
import './bar/bar-vertical-medium'
import './bar/bar-vertical-large'
import './bar/bar-vertical-positive-small'
import './bar/bar-vertical-positive-medium'
import './bar/bar-vertical-positive-large'

import './hdg/hdg-small'
import './hdg/hdg-medium'
import './hdg/hdg-large'

import './pitch-roll/pitch-small'
import './pitch-roll/pitch-medium'
import './pitch-roll/pitch-large'
import './pitch-roll/roll-small'
import './pitch-roll/roll-medium'
import './pitch-roll/roll-large'
import './pitch-roll/combined-small'
import './pitch-roll/combined-medium'
import './pitch-roll/combined-large'

import './rot/rot-circle-small'
import './rot/rot-circle-medium'
import './rot/rot-circle-large'
import './rot/rot-flat-small'
import './rot/rot-flat-medium'
import './rot/rot-flat-large'
import './rot/rot-flat-bar-small'
import './rot/rot-flat-bar-medium'
import './rot/rot-flat-bar-large'

import './rudder/rudder-small'
import './rudder/rudder-medium'
import './rudder/rudder-large'

import './sog/speedometer-medium'

import './thrusters/azimuth-small'
import './thrusters/azimuth-medium'
import './thrusters/azimuth-large'
import './thrusters/main-engine-small'
import './thrusters/main-engine-medium'
import './thrusters/main-engine-large'
import './thrusters/thruster-element-small'
import './thrusters/thruster-element-medium'
import './thrusters/thruster-element-large'
import './thrusters/tunnel-thruster-small'
import './thrusters/tunnel-thruster-medium'
import './thrusters/tunnel-thruster-large'

import './watchface/watchface-small'
import './watchface/watchface-medium'
import './watchface/watchface-large'
